/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateProjekt = /* GraphQL */ `
  subscription OnCreateProjekt {
    onCreateProjekt {
      id
      name
      Kategorie
      Finanzierungsvolumen
      ErwRendite
      Mindestinvestition
      Typ
      TitleLink
      LogoLink
      KurzBeschreibung
      KategorieBildLink
      InternerLink
      ExternerLink
      Help
      Blockchain
      Anbieter
      Behoerde
      Gruendung
      Emissionszeitraum
      WpPG
      Rechtsform
      Geschaeftstaetigkeit
      Ort
      Firmenname
      Emittent
      Rechtliche_Bezeichnung
      Zahlungsmoeglichkeiten
      Token_Ticker
      Max_Token_Anzahl
      ISIN
      ITIN
      description
      Update
      FilterTyp
      FilterRendite
      FilterFinanzierungsvolumen
      ProgWertentwicklung
      ProgDurchschnittsrendite
      checkBasisinformationsblatt
      checkWertpapierprospekt
      checkRisiken
      checkSchuldverschreibungsbedingungen
      check
      Laufzeitbeginn
      NaechsteAusschuettung
      Laufzeitende
      check_VI
      check_MWE
      check_KE
      Doks_Counter
      MIohneEuro
      FVohneEuro
      LaufzeitBeginMMMJJJJ
      LaufzeitEndeMMMJJJJ
      gesRendite
      DurchschnittRendite
      Wertentwicklung
      TokenAnzahlOhneFormat
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateProjekt = /* GraphQL */ `
  subscription OnUpdateProjekt {
    onUpdateProjekt {
      id
      name
      Kategorie
      Finanzierungsvolumen
      ErwRendite
      Mindestinvestition
      Typ
      TitleLink
      LogoLink
      KurzBeschreibung
      KategorieBildLink
      InternerLink
      ExternerLink
      Help
      Blockchain
      Anbieter
      Behoerde
      Gruendung
      Emissionszeitraum
      WpPG
      Rechtsform
      Geschaeftstaetigkeit
      Ort
      Firmenname
      Emittent
      Rechtliche_Bezeichnung
      Zahlungsmoeglichkeiten
      Token_Ticker
      Max_Token_Anzahl
      ISIN
      ITIN
      description
      Update
      FilterTyp
      FilterRendite
      FilterFinanzierungsvolumen
      ProgWertentwicklung
      ProgDurchschnittsrendite
      checkBasisinformationsblatt
      checkWertpapierprospekt
      checkRisiken
      checkSchuldverschreibungsbedingungen
      check
      Laufzeitbeginn
      NaechsteAusschuettung
      Laufzeitende
      check_VI
      check_MWE
      check_KE
      Doks_Counter
      MIohneEuro
      FVohneEuro
      LaufzeitBeginMMMJJJJ
      LaufzeitEndeMMMJJJJ
      gesRendite
      DurchschnittRendite
      Wertentwicklung
      TokenAnzahlOhneFormat
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteProjekt = /* GraphQL */ `
  subscription OnDeleteProjekt {
    onDeleteProjekt {
      id
      name
      Kategorie
      Finanzierungsvolumen
      ErwRendite
      Mindestinvestition
      Typ
      TitleLink
      LogoLink
      KurzBeschreibung
      KategorieBildLink
      InternerLink
      ExternerLink
      Help
      Blockchain
      Anbieter
      Behoerde
      Gruendung
      Emissionszeitraum
      WpPG
      Rechtsform
      Geschaeftstaetigkeit
      Ort
      Firmenname
      Emittent
      Rechtliche_Bezeichnung
      Zahlungsmoeglichkeiten
      Token_Ticker
      Max_Token_Anzahl
      ISIN
      ITIN
      description
      Update
      FilterTyp
      FilterRendite
      FilterFinanzierungsvolumen
      ProgWertentwicklung
      ProgDurchschnittsrendite
      checkBasisinformationsblatt
      checkWertpapierprospekt
      checkRisiken
      checkSchuldverschreibungsbedingungen
      check
      Laufzeitbeginn
      NaechsteAusschuettung
      Laufzeitende
      check_VI
      check_MWE
      check_KE
      Doks_Counter
      MIohneEuro
      FVohneEuro
      LaufzeitBeginMMMJJJJ
      LaufzeitEndeMMMJJJJ
      gesRendite
      DurchschnittRendite
      Wertentwicklung
      TokenAnzahlOhneFormat
      createdAt
      updatedAt
    }
  }
`;
